//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gruzin.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesStaff
    {
        public int IdCoursesStaff { get; set; }
        public int IdCourses { get; set; }
        public int IdStaff { get; set; }
        public int IdPayment { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
